#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
import random

# generated by online-judge-template-generator v4.4.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    # n = random.randint(1, 10)  # TODO: edit here
    n = 10
    x = [None for _ in range(n)]
    y = [None for _ in range(n)]
    # m = random.randint(1, 10)  # TODO: edit here
    m = 10
    a = [None for _ in range(m)]
    for i in range(n):
        x[i] = random.randint(1, 10 ** 2)  # TODO: edit here
        y[i] = random.randint(1, 10 ** 2)  # TODO: edit here
    for i in range(m):
        a[i] = random.randint(1, 10 ** 2)  # TODO: edit here
    print(n, m)
    for i in range(n):
        print(x[i], y[i])
    for i in range(m):
        print(a[i])

if __name__ == "__main__":
    main()
